CXXFLAGS = -O2 -g -Wall -fmessage-length=0

OBJS = main.cpp

HEADER_DIR = /home/hc/git_repo/gitLearner/observer/

TARGET = observer
$(TARGET): $(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)
all:	$(TARGET)
clean:
	rm -r $(TARGET)
